---
- name: Configure Nginx and Write to index.html
  hosts: all
  become: true
  tasks:
    - name: Install Nginx package
      package:
        name: nginx
        state: absent 

  #   - name: Create index.html file
  #     template:
  #       src: index.html.j2  # This is the template file
  #       dest: /usr/share/nginx/html/index.html
  #     notify: Restart Nginx

  # handlers:
  #   - name: Restart Nginx
  #     service:
  #       name: nginx
  #       state: restarted
